import { Activity, Boxes, MapPinned, Radio, Warehouse } from 'lucide-react'

import { OperationalShell } from '@/shared/layouts/OperationalShell'

import { useYardMetricsRuntime, useYardMovementsRuntime, useYardSlotsRuntime } from '../hooks/queries/useYardRuntime'

const number = (value = 0) => new Intl.NumberFormat('vi-VN', { maximumFractionDigits: 2 }).format(value)

export function YardPage() {
  const { data: slots = [] } = useYardSlotsRuntime()
  const { data: metrics } = useYardMetricsRuntime()
  const { data: movements = [] } = useYardMovementsRuntime()

  return <OperationalShell><main className="min-h-screen bg-[#020811] p-4 text-slate-100">
    <header className="mb-4 flex items-end justify-between"><div><p className="text-[10px] font-semibold uppercase tracking-[0.18em] text-cyan-400">Spatial operations runtime</p><h1 className="mt-1 text-2xl font-semibold">Bãi tập kết thành phẩm</h1><p className="mt-1 text-xs text-slate-400">Production → QC → Yard storage · dữ liệu placement thực từ Yard engine</p></div><span className="flex items-center gap-2 rounded border border-emerald-800 bg-emerald-950/30 px-3 py-2 text-xs text-emerald-300"><Radio size={14}/> LIVE 5s</span></header>
    <section className="grid gap-3 md:grid-cols-5">{[{Icon:Warehouse,label:'Khu vực',value:metrics?.zones},{Icon:MapPinned,label:'Tổng slot',value:metrics?.totalSlots},{Icon:Boxes,label:'Đang sử dụng',value:metrics?.occupiedSlots},{Icon:Activity,label:'Cấu kiện lưu bãi',value:metrics?.placements},{Icon:Radio,label:'Occupancy',value:`${metrics?.occupancyRate??0}%`}].map(({Icon,label,value})=><div key={label} className="rounded-lg border border-slate-800 bg-[#071321] p-4"><Icon size={17} className="text-cyan-400"/><div className="mt-3 text-[10px] uppercase text-slate-500">{label}</div><div className="mt-1 text-xl font-semibold">{value??0}</div></div>)}</section>
    <div className="mt-3 grid gap-3 xl:grid-cols-[1fr_330px]">
      <section className="rounded-lg border border-slate-800 bg-[#071321]"><header className="flex justify-between border-b border-slate-800 p-4"><div><h2 className="text-sm font-semibold">Sơ đồ slot vận hành</h2><p className="mt-1 text-xs text-slate-500">Click logic đã dùng placement thật; slot trống vẫn giữ khả năng xếp tầng.</p></div><span className="text-xs text-cyan-300">{slots.length} slots</span></header><div className="grid gap-2 p-3 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">{slots.map(slot=><article key={slot.id} className={`min-h-36 rounded border p-3 ${slot.placements.length?'border-cyan-700 bg-cyan-950/20':'border-slate-800 bg-slate-950/60'}`}><div className="flex justify-between"><div><div className="text-[10px] uppercase text-slate-500">{slot.zone.code}</div><div className="mt-1 text-lg font-semibold text-cyan-200">{slot.code}</div></div><span className="text-[10px] text-slate-400">L{slot.currentStackLevel}/{slot.maxStackLevel}</span></div><div className="mt-3 space-y-2">{slot.placements.map(item=><div key={item.id} className="rounded border border-slate-800 bg-black/30 p-2"><div className="text-xs text-cyan-300">{item.itemCode}</div><div className="mt-1 truncate text-[11px] text-slate-300">{item.itemName??item.itemType}</div><div className="mt-1 text-[10px] text-slate-500">SL {number(item.quantity)} · tầng L{item.stackLevel}</div></div>)}{slot.placements.length===0&&<div className="pt-5 text-center text-xs text-slate-600">Sẵn sàng tiếp nhận</div>}</div></article>)}</div>{slots.length===0&&<div className="p-12 text-center text-sm text-slate-500">Chưa có zone/slot bãi. Tạo cấu hình slot trước khi chuyển thành phẩm.</div>}</section>
      <aside className="space-y-3"><section className="rounded-lg border border-slate-800 bg-[#071321] p-4"><h2 className="text-sm font-semibold">Áp lực theo khu vực</h2><div className="mt-4 space-y-4">{(metrics?.zoneUtilization??[]).map(zone=><div key={zone.id}><div className="mb-1 flex justify-between text-xs"><span>{zone.code} · {zone.name}</span><span>{zone.occupancyRate}%</span></div><div className="h-1.5 rounded bg-slate-800"><div className={`h-full rounded ${zone.occupancyRate>80?'bg-red-500':zone.occupancyRate>50?'bg-amber-500':'bg-emerald-500'}`} style={{width:`${zone.occupancyRate}%`}}/></div></div>)}</div></section><section className="rounded-lg border border-slate-800 bg-[#071321] p-4"><h2 className="text-sm font-semibold">Di chuyển gần đây</h2><div className="mt-4 space-y-3">{movements.map(item=><div className="border-l border-cyan-700 pl-3 text-xs" key={item.id}><div className="text-cyan-300">{item.itemCode} · {item.type}</div><div className="mt-1 text-slate-500">{item.fromSlot?.code??'Xưởng'} → {item.toSlot?.code??'Rời bãi'} · {new Date(item.createdAt).toLocaleString('vi-VN')}</div></div>)}</div></section></aside>
    </div>
  </main></OperationalShell>
}
