packages:
  - "apps/*"
  - "packages/*"
overrides:
  dompurify: 3.4.13
  form-data: 4.0.6
  multer: 2.2.0
  socket.io-parser: 4.2.7
  ws: 8.21.0
allowBuilds:
  '@nestjs/core': true
  '@prisma/client': true
  '@prisma/engines': true
  bcrypt: true
  core-js: true
  esbuild: true
  prisma: true
  sharp: true
  tesseract.js: true
  unrs-resolver: true
