ALTER TABLE "yard_item_placements"
  ADD COLUMN IF NOT EXISTS "stagedQuantity" DOUBLE PRECISION NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "remainingQuantity" DOUBLE PRECISION NOT NULL DEFAULT 0;
